services:
  react-book-app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    init: true
    command: /bin/sh -c "while sleep 1000; do :; done"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ..:/home/node/workspace:cached
    working_dir: /home/node/workspace
